apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goal-tracker-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/itsbaivab/gitops-configs.git
    targetRevision: HEAD
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: goal-tracker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
