services:
  app:
    build:
      context: ../
      dockerfile: ./Dockerfile
    container_name: goal-tracker-app
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=goalsdb
      - SSL=disable
      - KO_DATA_PATH=/kodata
    volumes:
      - ../kodata:/kodata
    depends_on:
      - postgres
    networks:
      - goal-tracker-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: goal-tracker-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goalsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - goal-tracker-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: goal-tracker-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus-config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - goal-tracker-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: goal-tracker-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - goal-tracker-network
    restart: unless-stopped

networks:
  goal-tracker-network:
    driver: bridge

volumes:
  postgres-data:
  grafana-data: